[package]
name = "rustsync"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
dotenv = "0.15.0"
mysql_async = "0.35.1"
tiberius = "0.12.3"
tokio = { version = "1.44.0", features = ["full"] }
tokio-util = { version = "0.7.13", features = ["full"]}
